(function(){
'use strict';
const $=id=>document.getElementById(id),canvas=$('gameCanvas'),mini=$('mini');
if(!canvas||!mini)return;
const ctx=canvas.getContext('2d'),mctx=mini.getContext('2d'),TAU=Math.PI*2;
const POWER_STYLE={speed:['⚡','#fde047'],shield:['🛡️','#60a5fa'],magnet:['🧲','#c084fc'],growth:['✚','#34d399'],coin:['💰','#f59e0b']};
let socket=null,reconnectTimer=0,reconnectAttempts=0,pendingJoin=false,wantsToPlay=false,alive=false,selfId='',worldSize=5600;
let snapshot=emptySnapshot(),lastFrame=performance.now(),lastInputSent=0,pingAt=0,latency=0,dpr=1,animationFrame=0,manualZoom=1;
let mouse={x:0,y:0,wx:worldSize/2,wy:worldSize/2},camera={x:worldSize/2,y:worldSize/2,zoom:1};
const displayCells=new Map(),imageCache=new Map();
function emptySnapshot(){return{entities:{cells:[],food:[],viruses:[],powers:[],ejected:[]},powers:{},leaderboard:[],players:0,rewards:{food:0,kills:0,coins:0}}}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function serverUrl(){const q=new URLSearchParams(location.search).get('server'),saved=localStorage.getItem('pearlServerUrl'),configured=q||window.PEARL_SERVER_URL||saved||'';if(configured){const base=configured.replace(/^http:/,'ws:').replace(/^https:/,'wss:').replace(/\/+$/,'');return base.endsWith('/arena')?base:base+'/arena'}return(location.protocol==='https:'?'wss:':'ws:')+'//'+location.host+'/arena'}
function setConnectionStatus(text,state){const el=$('serverStatus');if(!el)return;el.textContent=text;el.className='pill serverStatus '+(state||'')}
function send(message){if(socket&&socket.readyState===WebSocket.OPEN){socket.send(JSON.stringify(message));return true}return false}
function connect(){clearTimeout(reconnectTimer);if(socket&&(socket.readyState===WebSocket.OPEN||socket.readyState===WebSocket.CONNECTING))return;setConnectionStatus('Connecting to public arena...','connecting');try{socket=new WebSocket(serverUrl())}catch(error){scheduleReconnect();return}socket.addEventListener('open',()=>{reconnectAttempts=0;setConnectionStatus('Public arena online','online');if(pendingJoin||wantsToPlay)joinArena()});socket.addEventListener('message',event=>{let message;try{message=JSON.parse(event.data)}catch(error){return}handleMessage(message)});socket.addEventListener('close',()=>{alive=false;setConnectionStatus('Reconnecting to public arena...','offline');scheduleReconnect()});socket.addEventListener('error',()=>setConnectionStatus('Arena connection failed','offline'))}
function scheduleReconnect(){clearTimeout(reconnectTimer);const delay=Math.min(10000,1000*Math.pow(1.7,reconnectAttempts++));reconnectTimer=setTimeout(connect,delay)}
function handleMessage(message){if(!message||typeof message!=='object')return;if(message.type==='hello'){selfId=message.id;worldSize=message.world||worldSize;if(pendingJoin||wantsToPlay)joinArena();return}if(message.type==='joined'){selfId=message.id;worldSize=message.world||worldSize;alive=true;pendingJoin=false;setConnectionStatus('Public arena online','online');hideOverlay();const profile=window.PEARL_PROFILE;if(profile&&profile.runStarted)profile.runStarted();return}if(message.type==='dead'){alive=false;wantsToPlay=false;showOverlay('You were eaten','Respawn to rejoin the same public arena.');return}if(message.type==='pong'){latency=Math.max(0,Math.round(performance.now()-Number(message.time||performance.now())));return}if(message.type==='snapshot'){snapshot=message;alive=Boolean(message.alive);if(alive)setConnectionStatus('Public arena online','online');worldSize=message.world||worldSize;applyRewards(message.rewards||{});updateDisplayTargets(message.entities.cells||[]);if(!alive&&wantsToPlay)showOverlay('Waiting for spawn','Connecting you to the public arena...')}}
function applyRewards(rewards){if(!rewards.food&&!rewards.kills&&!rewards.coins)return;const profile=window.PEARL_PROFILE;if(profile&&profile.award)profile.award(rewards)}
function joinArena(){wantsToPlay=true;pendingJoin=true;connect();if(!socket||socket.readyState!==WebSocket.OPEN){showOverlay('Connecting...','The public arena is waking up or reconnecting.');return}const profile=window.PEARL_PROFILE,skin=profile&&profile.getSkin?profile.getSkin():0,name=($('playerName').value||'PearlConsumer').slice(0,18);send({type:'join',name,skin});setConnectionStatus('Joining public arena...','connecting')}
function action(name){if(alive)send({type:'action',action:name})}
function showOverlay(title,text){const overlay=$('spawnOverlay');if(!overlay)return;overlay.style.display='flex';const h=overlay.querySelector('h2'),p=overlay.querySelector('p');if(h)h.textContent=title;if(p)p.textContent=text}
function hideOverlay(){const overlay=$('spawnOverlay');if(overlay)overlay.style.display='none'}
function resize(){const rect=canvas.getBoundingClientRect();dpr=Math.min(2,devicePixelRatio||1);canvas.width=Math.max(800,Math.floor(rect.width*dpr));canvas.height=Math.max(520,Math.floor(rect.height*dpr))}
function cw(){return canvas.width/dpr}function ch(){return canvas.height/dpr}
function updateDisplayTargets(cells){const seen=new Set();for(const cell of cells){const id=cell[0];seen.add(id);let d=displayCells.get(id);if(!d){d={id,owner:cell[1],x:cell[2],y:cell[3],r:cell[4],tx:cell[2],ty:cell[3],tr:cell[4],skin:cell[5],name:cell[6],bot:Boolean(cell[7]),merge:cell[8],missing:0};displayCells.set(id,d)}d.owner=cell[1];d.tx=cell[2];d.ty=cell[3];d.tr=cell[4];d.skin=cell[5];d.name=cell[6];d.bot=Boolean(cell[7]);d.merge=cell[8];d.missing=0}for(const d of displayCells.values()){if(!seen.has(d.id))d.missing++;if(d.missing>3)displayCells.delete(d.id)}}
function interpolateCells(dt){const amount=1-Math.pow(.0008,dt);for(const cell of displayCells.values()){cell.x+=(cell.tx-cell.x)*amount;cell.y+=(cell.ty-cell.y)*amount;cell.r+=(cell.tr-cell.r)*amount}}
function ownCells(){return Array.from(displayCells.values()).filter(cell=>cell.owner===selfId)}
function centerOf(cells){let x=0,y=0,w=0;for(const cell of cells){const a=cell.r*cell.r;x+=cell.x*a;y+=cell.y*a;w+=a}return w?{x:x/w,y:y/w}:{x:worldSize/2,y:worldSize/2}}
function updateCamera(){const cells=ownCells();if(!cells.length)return;const center=centerOf(cells),amount=cells.reduce((s,c)=>s+c.r*c.r/100,0);camera.x+=(center.x-camera.x)*.09;camera.y+=(center.y-camera.y)*.09;camera.zoom+=(clamp(1.28-amount/900,.42,1.18)*manualZoom-camera.zoom)*.05;mouse.wx=camera.x+(mouse.x-cw()/2)/camera.zoom;mouse.wy=camera.y+(mouse.y-ch()/2)/camera.zoom}
function worldToScreen(x,y){return{x:(x-camera.x)*camera.zoom+cw()/2,y:(y-camera.y)*camera.zoom+ch()/2}}
function skinFor(index){const skins=window.PEARL_SKINS||[];return skins[index]||skins[0]||{color:'#ff3366',icon:'●',name:'Core',img:''}}
function imageFor(skin){if(!skin.img)return null;if(!imageCache.has(skin.img)){const image=new Image();image.src=skin.img;imageCache.set(skin.img,image)}return imageCache.get(skin.img)}
function drawCell(cell){const point=worldToScreen(cell.x,cell.y),radius=cell.r*camera.zoom;if(point.x+radius<-80||point.x-radius>cw()+80||point.y+radius<-80||point.y-radius>ch()+80)return;const skin=skinFor(cell.skin),image=imageFor(skin);ctx.save();ctx.beginPath();ctx.arc(point.x,point.y,radius,0,TAU);const gradient=ctx.createRadialGradient(point.x-radius*.3,point.y-radius*.4,radius*.1,point.x,point.y,radius);gradient.addColorStop(0,'#fff');gradient.addColorStop(.18,skin.color||'#ff3366');gradient.addColorStop(1,'#111');ctx.fillStyle=gradient;ctx.fill();if(image&&image.complete&&image.naturalWidth){ctx.save();ctx.beginPath();ctx.arc(point.x,point.y,Math.max(0,radius-1),0,TAU);ctx.clip();const scale=Math.max(radius*2.25/image.naturalWidth,radius*2.25/image.naturalHeight),width=image.naturalWidth*scale,height=image.naturalHeight*scale;ctx.drawImage(image,point.x-width/2,point.y-height/2,width,height);ctx.restore()}else{ctx.fillStyle=skin.color==='#ffffff'?'#111':'#fff';ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='900 '+clamp(radius*.42,12,28)+'px system-ui';ctx.fillText(skin.icon||'●',point.x,point.y-radius*.08)}ctx.lineWidth=cell.owner===selfId?4:2;ctx.strokeStyle=cell.owner===selfId?'rgba(255,255,255,.88)':'rgba(0,0,0,.62)';ctx.stroke();if(cell.owner===selfId&&snapshot.powers.shield>0){ctx.beginPath();ctx.arc(point.x,point.y,radius+7,0,TAU);ctx.strokeStyle='rgba(96,165,250,.85)';ctx.lineWidth=4;ctx.stroke()}ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='800 '+clamp(radius*.2,9,14)+'px system-ui';ctx.strokeStyle='rgba(0,0,0,.85)';ctx.lineWidth=3;ctx.strokeText(cell.name||'',point.x,point.y-radius-12);ctx.fillStyle='#fff';ctx.fillText(cell.name||'',point.x,point.y-radius-12);if(radius>20){ctx.font='900 '+clamp(radius*.18,9,15)+'px system-ui';const value=Math.floor(cell.r*cell.r/100);ctx.strokeText(value,point.x,point.y+radius*.38);ctx.fillText(value,point.x,point.y+radius*.38)}ctx.restore()}
function drawWorld(){ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,cw(),ch());ctx.fillStyle='#06060b';ctx.fillRect(0,0,cw(),ch());ctx.save();ctx.translate(cw()/2,ch()/2);ctx.scale(camera.zoom,camera.zoom);ctx.translate(-camera.x,-camera.y);const visibleWidth=cw()/camera.zoom,visibleHeight=ch()/camera.zoom,left=camera.x-visibleWidth/2,top=camera.y-visibleHeight/2;ctx.strokeStyle='rgba(255,255,255,.045)';ctx.lineWidth=1/camera.zoom;for(let x=Math.floor(left/120)*120;x<left+visibleWidth+120;x+=120){ctx.beginPath();ctx.moveTo(x,top);ctx.lineTo(x,top+visibleHeight+120);ctx.stroke()}for(let y=Math.floor(top/120)*120;y<top+visibleHeight+120;y+=120){ctx.beginPath();ctx.moveTo(left,y);ctx.lineTo(left+visibleWidth+120,y);ctx.stroke()}ctx.strokeStyle='rgba(255,51,102,.72)';ctx.lineWidth=7/camera.zoom;ctx.strokeRect(0,0,worldSize,worldSize);for(const item of snapshot.entities.food){ctx.beginPath();ctx.arc(item[0],item[1],item[2],0,TAU);ctx.fillStyle='hsl('+item[3]+' 88% 62%)';ctx.fill()}for(const item of snapshot.entities.ejected){const skin=skinFor(item[4]);ctx.beginPath();ctx.arc(item[1],item[2],item[3],0,TAU);ctx.fillStyle=skin.color||'#fff';ctx.fill()}for(const item of snapshot.entities.viruses){ctx.save();ctx.beginPath();for(let index=0;index<22;index++){const angle=index/22*TAU,radius=item[2]+(index%2?5:-3),x=item[0]+Math.cos(angle)*radius,y=item[1]+Math.sin(angle)*radius;if(index)ctx.lineTo(x,y);else ctx.moveTo(x,y)}ctx.closePath();ctx.fillStyle='rgba(34,197,94,.34)';ctx.fill();ctx.strokeStyle='#22c55e';ctx.lineWidth=3/camera.zoom;ctx.stroke();ctx.restore()}for(const item of snapshot.entities.powers){const style=POWER_STYLE[item[3]]||['?','#fff'];ctx.save();ctx.shadowColor=style[1];ctx.shadowBlur=30;ctx.beginPath();ctx.arc(item[1],item[2],23,0,TAU);ctx.fillStyle='rgba(255,255,255,.10)';ctx.fill();ctx.lineWidth=4/camera.zoom;ctx.strokeStyle=style[1];ctx.stroke();ctx.font='24px serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(style[0],item[1],item[2]);ctx.restore()}ctx.restore();Array.from(displayCells.values()).sort((a,b)=>a.r-b.r).forEach(drawCell)}
function drawMini(){mctx.clearRect(0,0,160,160);mctx.fillStyle='rgba(0,0,0,.65)';mctx.fillRect(0,0,160,160);const scale=160/worldSize;for(const cell of displayCells.values()){mctx.beginPath();mctx.arc(cell.x*scale,cell.y*scale,cell.owner===selfId?3:1.8,0,TAU);mctx.fillStyle=cell.owner===selfId?'#ff3366':cell.bot?'#a78bfa':'#22d3ee';mctx.fill()}mctx.strokeStyle='rgba(255,255,255,.35)';mctx.strokeRect(0,0,160,160)}
function updateHud(){if(alive)setConnectionStatus('Public arena online','online');const cells=ownCells(),amount=cells.reduce((s,c)=>s+c.r*c.r/100,0),largest=cells.reduce((v,c)=>Math.max(v,c.r*c.r/100),0),merge=cells.length>1?Math.max(0,Math.min(...cells.map(c=>c.merge))):0;$('hud').innerHTML='<span class="pill">ONLINE</span><span class="pill">Players '+(snapshot.players||0)+'</span><span class="pill">Mass '+Math.floor(amount)+'</span><span class="pill">Cells '+cells.length+'</span><span class="pill">Largest '+Math.floor(largest)+'</span><span class="pill">Merge '+(merge>0?merge+'s':'READY')+'</span><span class="pill">Ping '+latency+'ms</span>';$('powerBar').innerHTML=Object.keys(snapshot.powers||{}).map(key=>'<span class="powerChip">'+key.toUpperCase()+' '+Number(snapshot.powers[key]).toFixed(1)+'s</span>').join('');$('leaderboard').innerHTML=(snapshot.leaderboard||[]).map((row,index)=>'<div style="'+(row.id===selfId?'color:#ff8aaa;font-weight:950':'')+'">'+(index+1)+'. '+escapeHtml(row.name)+' <span class="muted">'+row.mass+'</span> '+(row.bot?'<span class="muted">bot</span>':'<span style="color:#67e8f9">player</span>')+'</div>').join('');const count=$('onlineCount');if(count)count.textContent=String(snapshot.players||0);const profile=window.PEARL_PROFILE;if(profile&&profile.observeMass)profile.observeMass(amount)}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'})[c])}
function sendInput(time){if(!alive||time-lastInputSent<45)return;lastInputSent=time;send({type:'input',x:mouse.wx,y:mouse.wy});if(time-pingAt>3000){pingAt=time;send({type:'ping',time})}}
function loop(time){const dt=Math.min(.05,(time-lastFrame)/1000||.016);lastFrame=time;interpolateCells(dt);updateCamera();sendInput(time);drawWorld();drawMini();updateHud();animationFrame=requestAnimationFrame(loop)}
function pointer(event){const point=event.touches?event.touches[0]:event,rect=canvas.getBoundingClientRect();mouse.x=point.clientX-rect.left;mouse.y=point.clientY-rect.top;if(event.cancelable)event.preventDefault()}
$('spawnBtn').addEventListener('click',joinArena);$('overlaySpawn').addEventListener('click',joinArena);$('splitBtn').addEventListener('click',()=>action('split'));$('ejectBtn').addEventListener('click',()=>action('eject'));$('mergeBtn').addEventListener('click',()=>action('merge'));canvas.addEventListener('mousemove',pointer);canvas.addEventListener('touchmove',pointer,{passive:false});canvas.addEventListener('wheel',event=>{event.preventDefault();manualZoom=clamp(manualZoom+(event.deltaY>0?-.08:.08),.68,1.55)},{passive:false});window.addEventListener('keydown',event=>{const gameTab=document.getElementById('game');if(!alive||!gameTab||!gameTab.classList.contains('active'))return;if(event.code==='Space'){event.preventDefault();action('split')}if(event.code==='KeyW'){event.preventDefault();action('eject')}if(event.code==='KeyQ'){event.preventDefault();action('merge')}});window.addEventListener('resize',resize);window.addEventListener('beforeunload',()=>{clearTimeout(reconnectTimer);if(socket)socket.close();cancelAnimationFrame(animationFrame)});resize();connect();animationFrame=requestAnimationFrame(loop);
})();
