services:
  - type: web
    name: pearl-io-public-arena
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    numInstances: 1
    autoDeployTrigger: commit
